// @provenance rule: rule_docs_no_annotations
import type { LoadedRequest } from "../gen/load.ts";
import { substituteEnvRefs } from "../save/credentials.ts";
import { REDACTED, isCredentialHeader } from "../send/redact.ts";

const TITLE = "# API reference";
const BANNER =
  "<!-- Generated by postui docs from requests/ — do not edit; regenerate with `postui docs`. -->";

/**
 * Render every loaded request as one markdown document, in the given
 * (folder-sorted) order: a section per request with its method, URL,
 * headers, and body.
 */
export function renderDocs(requests: LoadedRequest[]): string {
  const parts: string[] = [TITLE, "", BANNER];
  for (const loaded of requests) {
    parts.push("", renderRequest(loaded));
  }
  return parts.join("\n") + "\n";
}

/** Show every $NAME / ${NAME} reference as `requires NAME env`; resolve nothing. */
function displayEnv(text: string): string {
  return substituteEnvRefs(text, name => `requires ${name} env`);
}

function renderRequest(loaded: LoadedRequest): string {
  const request = loaded.request;
  const lines: string[] = [
    `## ${loaded.name}`,
    "",
    `- method: ${request.method}`,
    `- url: ${displayEnv(request.url)}`,
    "",
    "### headers",
    "",
  ];
  const headers = Object.entries(request.headers);
  if (headers.length === 0) {
    lines.push("none", "");
  } else {
    for (const [name, value] of headers) {
      const shown = isCredentialHeader(name) ? REDACTED : displayEnv(value);
      lines.push(`- ${name}: ${shown}`);
    }
    lines.push("");
  }
  lines.push("### body", "");
  lines.push(...renderBody(request.body));
  return lines.join("\n");
}

function renderBody(
  body: null | string | Array<{ name: string; value?: string; file?: string }>,
): string[] {
  if (body === null) return ["none"];
  if (typeof body === "string") return fenced(displayEnv(body));
  if (body.length === 0) return ["none"];
  const lines: string[] = [];
  for (const entry of body) {
    if (entry.file !== undefined) {
      lines.push(`- ${entry.name} (file): ${displayEnv(entry.file)}`);
    } else {
      const shown = isCredentialHeader(entry.name) ? REDACTED : displayEnv(entry.value ?? "");
      lines.push(`- ${entry.name}: ${shown}`);
    }
  }
  return lines;
}

/**
 * A fenced code block tall enough to contain every backtick run the text
 * itself carries, so a body full of backticks cannot end its own fence.
 */
function fenced(text: string): string[] {
  let longestRun = 0;
  for (const run of text.match(/`+/g) ?? []) {
    if (run.length > longestRun) longestRun = run.length;
  }
  const fence = "`".repeat(Math.max(3, longestRun + 1));
  return [fence, text, fence];
}
