import { afterAll, describe, expect, test } from "bun:test";
import { RGBA } from "@opentui/core";
import { createTestRenderer } from "@opentui/core/testing";
import {
  focusComposer,
  focusResponse,
  HEIGHT,
  moduleSource,
  openFirstRequest,
  serve,
  setupApp,
  teardownApps,
} from "./helpers/tui-app.ts";
import type { AppSetup } from "./helpers/tui-app.ts";
import { MAX_BODY_WINDOW, startResponsePane } from "../src/tui/response-pane.ts";
import { THEME } from "../src/tui/theme.ts";
import { frameText } from "./helpers/tui-capture.ts";

const CANARY = "agent-secret-91af";

afterAll(async () => {
  delete process.env.POSTUI_TEST_TOKEN;
  await teardownApps();
});

/** Open the first request, send it, settle. */
async function sendFromApp(app: AppSetup): Promise<void> {
  await openFirstRequest(app);
  await focusComposer(app);
  app.mockInput.pressEnter();
  await app.flush();
  await app.shell.composer.settled();
  await app.renderOnce();
}

describe("response pane", () => {
  test("redaction holds on every TUI path: an echoed credential shows [redacted]", async () => {
    // The server echoes the Authorization value back in the body AND in a
    // response header — both places a secret could try to surface.
    const server = serve(req => {
      const auth = req.headers.get("authorization") ?? "";
      return new Response(JSON.stringify({ youSent: auth, note: "hi" }), {
        status: 200,
        headers: { "x-echo-auth": auth },
      });
    });
    const app = await setupApp({
      "echo.ts": moduleSource("POST", server.url("/"), {
        headers: { authorization: `Bearer ${CANARY}` },
        body: '{"x":1}',
      }),
    });
    await sendFromApp(app);
    const text = frameText(app, HEIGHT);
    expect(text).toContain("[redacted]"); // the same marker as the CLI
    expect(text).not.toContain(CANARY); // nowhere, ever
    // HEADERS tab is scrubbed too
    await focusResponse(app);
    app.mockInput.pressKey("l"); // BODY → HEADERS
    await app.flush();
    await app.renderOnce();
    const headers = frameText(app, HEIGHT);
    expect(headers).toContain("x-echo-auth: [redacted]"); // structural redaction
    expect(headers).not.toContain(CANARY);
    server.close();
  });

  test("the status line colors success codes gold and shows latency and size", async () => {
    const server = serve(() => new Response(JSON.stringify({ ok: true }), { status: 200 }));
    const app = await setupApp({ "ok.ts": moduleSource("GET", server.url("/")) });
    await sendFromApp(app);
    const gold = RGBA.fromHex(THEME.color.gold);
    const spans = app.captureSpans().lines.flatMap(line => line.spans);
    const status = spans.find(span => span.text.includes("200 OK"));
    expect(status?.fg.equals(gold)).toBe(true);
    const text = frameText(app, HEIGHT);
    expect(text).toMatch(/\d+ ms/);
    expect(text).toContain("11 B"); // exact byte size of {"ok":true}
    server.close();
  });

  test("error statuses render in the accent red, not gold", async () => {
    const server = serve(() => new Response("no", { status: 403 }));
    const app = await setupApp({ "no.ts": moduleSource("GET", server.url("/")) });
    await sendFromApp(app);
    const accent = RGBA.fromHex(THEME.color.accent);
    const gold = RGBA.fromHex(THEME.color.gold);
    const spans = app.captureSpans().lines.flatMap(line => line.spans);
    const status = spans.find(span => span.text.includes("403"));
    expect(status?.fg.equals(accent)).toBe(true);
    expect(status?.fg.equals(gold)).toBe(false);
    server.close();
  });

  test("BODY/HEADERS/TESTS tabs switch with h/l", async () => {
    const server = serve(() => new Response("{}", { status: 200, headers: { "x-kind": "t" } }));
    const app = await setupApp({ "tabbed.ts": moduleSource("GET", server.url("/")) });
    await sendFromApp(app);
    await focusResponse(app);
    app.mockInput.pressKey("l"); // HEADERS
    await app.flush();
    await app.renderOnce();
    const headers = frameText(app, HEIGHT);
    expect(headers).toContain("HEADERS");
    expect(headers).toContain("x-kind: t");
    app.mockInput.pressKey("l"); // TESTS
    await app.flush();
    await app.renderOnce();
    const tests = frameText(app, HEIGHT);
    expect(tests).toContain("TESTS");
    expect(tests).toContain("no generated tests");
    expect(tests).toContain("run postui gen"); // the honest empty state
    app.mockInput.pressKey("h"); // HEADERS
    await app.flush();
    app.mockInput.pressKey("h"); // BODY
    await app.flush();
    await app.renderOnce();
    expect(frameText(app, HEIGHT)).toContain("(complete)");
    server.close();
  });

  test("TESTS tab lists the request's generated test when one exists (even before a send)", async () => {
    const server = serve(() => new Response("{}", { status: 200 }));
    const app = await setupApp(
      { "listed.ts": moduleSource("GET", server.url("/")) },
      { "listed.test.ts": '// Generated by postui gen (bun:test)\nimport test from "bun:test";\n' },
    );
    await openFirstRequest(app);
    await focusComposer(app);
    await focusResponse(app);
    app.mockInput.pressKey("l"); // HEADERS
    await app.flush();
    app.mockInput.pressKey("l"); // TESTS — before any send
    await app.flush();
    await app.shell.response.settled();
    await app.renderOnce();
    expect(frameText(app, HEIGHT)).toContain("tests/listed.test.ts");
    server.close();
  });

  test("+ widens the body window by re-sending through the pipeline", async () => {
    const tail = "tail-marker-4f21";
    const big = JSON.stringify({ pad: "x".repeat(400), tail });
    let hits = 0;
    const server = serve(() => {
      hits += 1;
      return new Response(big, { status: 200 });
    });
    const app = await setupApp({ "wide.ts": moduleSource("GET", server.url("/")) });
    await sendFromApp(app);
    const first = frameText(app, HEIGHT);
    expect(first).toContain("showing first 256 of"); // bounded by the default window
    expect(first).not.toContain(tail); // past the window
    await focusResponse(app);
    app.mockInput.pressKey("+"); // 256 → 512 bytes
    await app.flush();
    await app.shell.composer.settled();
    await app.renderOnce();
    const wider = frameText(app, HEIGHT);
    expect(hits).toBe(2); // widening re-sends: the CLI's --body-bytes semantics
    expect(wider).toContain(tail); // now within the window
    expect(wider).toContain("(complete)");
    server.close();
  });

  test("- narrows the window; widening steps the excerpt window up", async () => {
    const big = JSON.stringify({ pad: "y".repeat(3000) });
    const server = serve(() => new Response(big, { status: 200 }));
    const app = await setupApp({ "cap.ts": moduleSource("GET", server.url("/")) });
    await sendFromApp(app);
    await focusResponse(app);
    // Widening twice re-sends and widens the note: 256 → 512 → 1024 bytes.
    app.mockInput.pressKey("+");
    await app.flush();
    await app.shell.composer.settled();
    await app.renderOnce();
    expect(frameText(app, HEIGHT)).toContain("first 512 of");
    app.mockInput.pressKey("+");
    await app.flush();
    await app.shell.composer.settled();
    await app.renderOnce();
    expect(frameText(app, HEIGHT)).toContain("first 1024 of");
    // Narrowing shrinks the window again.
    app.mockInput.pressKey("-");
    await app.flush();
    await app.shell.composer.settled();
    await app.renderOnce();
    expect(frameText(app, HEIGHT)).toContain("first 512 of");
    server.close();
  });

  test("the 1 MiB cap: + at the cap consumes the key but stops widening", async () => {
    // Pane-level, no shell, no sends: the spy accepts every window change, so
    // mashing + must top out at MAX_BODY_WINDOW and never exceed it.
    const setup = await createTestRenderer({ width: 80, height: 12 });
    let accepted: number | null = null;
    const pane = startResponsePane(setup.renderer, {
      testsDir: "/nonexistent",
      onWindowChange: (window) => {
        accepted = window;
        return true;
      },
    });
    setup.renderer.root.add(pane.pane);
    pane.handleKey({ name: "+", ctrl: false }); // no result yet: inert
    expect(accepted).toBeNull();
    pane.showResult(
      {
        outcome: {
          kind: "sent",
          status: 200,
          request: { method: "GET", url: "u", headers: [], headersOmitted: 0 },
          response: {
            status: 200,
            headers: [],
            headersOmitted: 0,
            size: 1,
            shape: "opaque",
            excerpt: "x",
            excerptBytes: 1,
            truncated: false,
          },
          redirectedTo: null,
        },
        secrets: [],
      },
      1,
    );
    for (let i = 0; i < 40; i += 1) pane.handleKey({ name: "+", ctrl: false });
    expect(pane.bodyWindow).toBe(MAX_BODY_WINDOW);
    expect(accepted as number | null).toBe(MAX_BODY_WINDOW);
    setup.renderer.destroy();
  });

  test("a + during an in-flight re-send is refused and the window stays put", async () => {
    let hits = 0;
    const big = JSON.stringify({ pad: "p".repeat(2000) }); // 2010 bytes: truncated below 1 KiB window
    const server = serve(async () => {
      hits += 1;
      await Bun.sleep(60);
      return new Response(big, { status: 200 });
    });
    const app = await setupApp({ "slow.ts": moduleSource("GET", server.url("/")) });
    await sendFromApp(app);
    await focusResponse(app);
    app.mockInput.pressKey("+"); // starts the 256 → 512 re-send
    await app.flush();
    app.mockInput.pressKey("+"); // refused: a send is in flight
    await app.flush();
    await app.shell.composer.settled();
    await app.renderOnce();
    const text = frameText(app, HEIGHT);
    expect(text).toContain("window 512 B"); // exactly one widen landed
    expect(hits).toBe(2); // initial send + one widen, nothing extra
    server.close();
  });

  test("huge bodies stay bounded: the excerpt view caps its lines honestly", async () => {
    const huge = JSON.stringify({ pad: "z".repeat(300000) });
    const server = serve(() => new Response(huge, { status: 200 }));
    const app = await setupApp({ "huge.ts": moduleSource("GET", server.url("/")) });
    await sendFromApp(app);
    const text = frameText(app, HEIGHT);
    expect(text).toContain("293.0 KB"); // full size reported, formatted
    expect(text).toContain("showing first 256 of"); // excerpt stays bounded
    expect(text.length).toBeLessThan(20000); // the pane did not explode
    server.close();
  });

  test("a non-JSON response renders its excerpt and shape honestly", async () => {
    const server = serve(
      () => new Response("<html><body>ok</body></html>", { status: 200, headers: { "content-type": "text/html" } }),
    );
    const app = await setupApp({ "page.ts": moduleSource("GET", server.url("/")) });
    await sendFromApp(app);
    const text = frameText(app, HEIGHT);
    expect(text).toContain("text/html"); // the shape
    expect(text).toContain("<html><body>ok</body></html>");
    server.close();
  });

  test("a redirect surfaces the CLI's warning line", async () => {
    let followed = false;
    const server = serve(req => {
      const path = new URL(req.url).pathname;
      if (path === "/hop") {
        return new Response(null, { status: 302, headers: { location: "/final" } });
      }
      followed = true;
      return new Response("landed", { status: 200 });
    });
    const app = await setupApp({ "hop.ts": moduleSource("GET", server.url("/hop")) });
    await sendFromApp(app);
    const text = frameText(app, HEIGHT);
    expect(followed).toBe(true);
    expect(text).toContain("warning: followed redirect");
    expect(text).toContain("200 OK");
    server.close();
  });

  test("the response pane's keys do not leak to the global map (q still quits)", async () => {
    const app = await setupApp({ "one.ts": moduleSource("GET", "https://api.dev/one") });
    await openFirstRequest(app);
    await focusComposer(app);
    await focusResponse(app);
    let quit = false;
    void app.shell.onQuit.then(() => {
      quit = true;
      return quit;
    });
    app.mockInput.pressKey("q");
    await app.flush();
    expect(quit).toBe(true); // response pane fell through; the shell quit
  });
});
