import { afterAll, describe, expect, test } from "bun:test";
import { RGBA } from "@opentui/core";
import {
  focusComposer,
  focusResponse,
  HEIGHT,
  moduleSource,
  openFirstRequest,
  serve,
  setupApp,
  teardownApps,
} from "./helpers/tui-app.ts";
import type { AppSetup } from "./helpers/tui-app.ts";
import { TUI_BODY_WINDOW } from "../src/tui/response-pane.ts";
import { THEME } from "../src/tui/theme.ts";
import { frameText } from "./helpers/tui-capture.ts";

const CANARY = "agent-secret-91af";

afterAll(async () => {
  delete process.env.POSTUI_TEST_TOKEN;
  await teardownApps();
});

/** Open the first request, send it, settle. */
async function sendFromApp(app: AppSetup): Promise<void> {
  await openFirstRequest(app);
  await focusComposer(app);
  app.mockInput.pressEnter();
  await app.flush();
  await app.shell.composer.settled();
  await app.renderOnce();
}

describe("response pane", () => {
  test("redaction holds on every TUI path: an echoed credential shows [redacted]", async () => {
    // The server echoes the Authorization value back in the body AND in a
    // response header — both places a secret could try to surface.
    const server = serve(req => {
      const auth = req.headers.get("authorization") ?? "";
      return new Response(JSON.stringify({ youSent: auth, note: "hi" }), {
        status: 200,
        headers: { "x-echo-auth": auth },
      });
    });
    const app = await setupApp({
      "echo.ts": moduleSource("POST", server.url("/"), {
        headers: { authorization: `Bearer ${CANARY}` },
        body: '{"x":1}',
      }),
    });
    await sendFromApp(app);
    const text = frameText(app, HEIGHT);
    expect(text).toContain("[redacted]"); // the same marker as the CLI
    expect(text).not.toContain(CANARY); // nowhere, ever
    // HEADERS tab is scrubbed too
    await focusResponse(app);
    app.mockInput.pressKey("l"); // BODY → HEADERS
    await app.flush();
    await app.renderOnce();
    const headers = frameText(app, HEIGHT);
    expect(headers).toContain("x-echo-auth: [redacted]"); // structural redaction
    expect(headers).not.toContain(CANARY);
    server.close();
  });

  test("the status line colors success codes sage and shows latency and size", async () => {
    const server = serve(() => new Response(JSON.stringify({ ok: true }), { status: 200 }));
    const app = await setupApp({ "ok.ts": moduleSource("GET", server.url("/")) });
    await sendFromApp(app);
    const sage = RGBA.fromHex(THEME.color.sage);
    const spans = app.captureSpans().lines.flatMap(line => line.spans);
    const status = spans.find(span => span.text.includes("200 OK"));
    expect(status?.fg.equals(sage)).toBe(true);
    const text = frameText(app, HEIGHT);
    expect(text).toMatch(/\d+ ms/);
    expect(text).toContain("11 B"); // exact byte size of {"ok":true}
    server.close();
  });

  test("error statuses render in love, never the accent", async () => {
    const server = serve(() => new Response("no", { status: 403 }));
    const app = await setupApp({ "no.ts": moduleSource("GET", server.url("/")) });
    await sendFromApp(app);
    const love = RGBA.fromHex(THEME.color.love);
    const accent = RGBA.fromHex(THEME.color.accent);
    const spans = app.captureSpans().lines.flatMap(line => line.spans);
    // "403 FORBIDDEN", not bare "403": the server's random port may hold those digits.
    const status = spans.find(span => span.text.includes("403 FORBIDDEN"));
    expect(status?.fg.equals(love)).toBe(true);
    expect(status?.fg.equals(accent)).toBe(false);
    server.close();
  });

  test("BODY/HEADERS/TESTS tabs switch with h/l", async () => {
    const server = serve(() => new Response("{}", { status: 200, headers: { "x-kind": "t" } }));
    const app = await setupApp({ "tabbed.ts": moduleSource("GET", server.url("/")) });
    await sendFromApp(app);
    await focusResponse(app);
    app.mockInput.pressKey("l"); // HEADERS
    await app.flush();
    await app.renderOnce();
    const headers = frameText(app, HEIGHT);
    expect(headers).toContain("HEADERS");
    expect(headers).toContain("x-kind: t");
    app.mockInput.pressKey("l"); // TESTS
    await app.flush();
    await app.renderOnce();
    const tests = frameText(app, HEIGHT);
    expect(tests).toContain("TESTS");
    expect(tests).toContain("no generated tests");
    expect(tests).toContain("run postui gen"); // the honest empty state
    app.mockInput.pressKey("h"); // HEADERS
    await app.flush();
    app.mockInput.pressKey("h"); // BODY
    await app.flush();
    await app.renderOnce();
    expect(frameText(app, HEIGHT)).toContain("(complete)");
    server.close();
  });

  test("TESTS tab lists the request's generated test when one exists (even before a send)", async () => {
    const server = serve(() => new Response("{}", { status: 200 }));
    const app = await setupApp(
      { "listed.ts": moduleSource("GET", server.url("/")) },
      { "listed.test.ts": '// Generated by postui gen (bun:test)\nimport test from "bun:test";\n' },
    );
    await openFirstRequest(app);
    await focusComposer(app);
    await focusResponse(app);
    app.mockInput.pressKey("l"); // HEADERS
    await app.flush();
    app.mockInput.pressKey("l"); // TESTS — before any send
    await app.flush();
    await app.shell.response.settled();
    await app.renderOnce();
    expect(frameText(app, HEIGHT)).toContain("tests/listed.test.ts");
    server.close();
  });

  test("huge bodies stay bounded: the excerpt view caps its lines honestly", async () => {
    const huge = JSON.stringify({ pad: "z".repeat(300000) });
    const server = serve(() => new Response(huge, { status: 200 }));
    const app = await setupApp({ "huge.ts": moduleSource("GET", server.url("/")) });
    await sendFromApp(app);
    const text = frameText(app, HEIGHT);
    expect(text).toContain("293.0 KB"); // full size reported, formatted
    expect(text).toContain(`showing first ${TUI_BODY_WINDOW} of`); // excerpt stays bounded
    expect(text.length).toBeLessThan(20000); // the pane did not explode
    server.close();
  });

  test("a non-JSON response renders its excerpt and shape honestly", async () => {
    const server = serve(
      () => new Response("<html><body>ok</body></html>", { status: 200, headers: { "content-type": "text/html" } }),
    );
    const app = await setupApp({ "page.ts": moduleSource("GET", server.url("/")) });
    await sendFromApp(app);
    const text = frameText(app, HEIGHT);
    expect(text).toContain("text/html"); // the shape
    expect(text).toContain("<html><body>ok</body></html>");
    server.close();
  });

  test("a redirect surfaces the CLI's warning line", async () => {
    let followed = false;
    const server = serve(req => {
      const path = new URL(req.url).pathname;
      if (path === "/hop") {
        return new Response(null, { status: 302, headers: { location: "/final" } });
      }
      followed = true;
      return new Response("landed", { status: 200 });
    });
    const app = await setupApp({ "hop.ts": moduleSource("GET", server.url("/hop")) });
    await sendFromApp(app);
    const text = frameText(app, HEIGHT);
    expect(followed).toBe(true);
    expect(text).toContain("warning: followed redirect");
    expect(text).toContain("200 OK");
    server.close();
  });

  test("the response pane's keys do not leak to the global map (q still quits)", async () => {
    const app = await setupApp({ "one.ts": moduleSource("GET", "https://api.dev/one") });
    await openFirstRequest(app);
    await focusComposer(app);
    await focusResponse(app);
    let quit = false;
    void app.shell.onQuit.then(() => {
      quit = true;
      return quit;
    });
    app.mockInput.pressKey("q");
    await app.flush();
    expect(quit).toBe(true); // response pane fell through; the shell quit
  });
});
